### ISSUE TITLE
Multiple definition of lsame during compiling with shared version and internal blas

### ISSUE THREAD

**Issue by dvdesolve** [flame/libflame#26]
My system: Arch Linux 64 bit, latest updates, GCC 9.1.0. Configure line:
```
./configure --prefix=/usr --enable-static-build --enable-dynamic-build --enable-multithreading=openmp --enable-supermatrix --enable-max-arg-list-hack --enable-builtin-blas
```

Compiling with these settings (two processes for `make` step) gives me the following error at the very end:
```
Dynamically linking lib/x86_64-unknown-linux-gnu/libflame.so
/usr/bin/ld: obj/x86_64-unknown-linux-gnu/src/flablas/f2c/lsame.o: in function `lsame_':
lsame.c:(.text+0x0): multiple definition of `lsame_'; obj/x86_64-unknown-linux-gnu/src/map/lapack2flamec/f2c/install/static/lsame.o:lsame.c:(.text+0x0): first defined here
```

If I configure `libflame` without `--enable-builtin-blas` option then building works just fine and I get both static and dynamic libraries.

How it can be fixed?

**Comment by fgvanzee** [comment]
@dvdesolve Thanks for bringing this to our attention. I'll look into it.

In the meantime, I want to caution you that the built-in BLAS is **very** slow. Unless you have a really good reason to combine everything in a single library, I would highly recommend that you go with a two-library solution instead: libflame + [BLIS](https://github.com/flame/blis).

**Comment by dvdesolve** [comment]
The software that needs `libflame` (GAMESS-US) mentions that `libflame` + `BLIS` bindings gives a lot of significant numerical errors. I will re-check with latest GCC compilers (9.1.0) and see if this is true

**Comment by fgvanzee** [comment]
@dvdesolve Would you be able to contact those folks and ask them how to reproduce those numerical errors? We strive for BLIS to yield "correct" numerical output whenever possible, so if it's something that can be fixed, we definitely want to fix it.

**Comment by dvdesolve** [comment]
Ok, I will test on my systems and try to contact the GAMESS group. Thank for your efforts!

**Comment by fgvanzee** [comment]
@dvdesolve The numerical errors referred to above may be specific to the downstream version of BLIS maintained by AMD. I would **highly** encourage you and/or the GAMESS folks to try out our upstream version. AMD may include optimizations that may, in some cases, disrupt numerical behavior in ways that our plain vanilla version does not. (I am in fairly regular contact with the AMD team that manages the AMD fork of BLIS, and so if there are numerical issues, we should bring this to their attention. I imagine they will be just as interested in attempting to fix those issues as I am.) Or, perhaps the problem is actually in both versions, in which case I would be eager to look into the details and see if there was a way that I could accommodate your / GAMESS's needs.

**Comment by fgvanzee** [comment]
@dvdesolve I think I've fixed the `lsame_()` issue. Please try b0936fb and let me know if that works for you. (I started with your `configure` flags, and then tried enabling built-in BLAS, lapack2flame, neither, and both.)

**Comment by dvdesolve** [comment]
works just fine, thank you! Will test new BLIS soon
